import filecmp
import mock
import os
import sys

from fixtures import fixtures
from utils import testing_qualtrics_audit
from bu_tap_qualtrics import sync, discover

def test_sync():
    with mock.patch("bu_tap_qualtrics.qualtrics_audit", testing_qualtrics_audit) as _:
        test_output = "tests/unit/test.out"
        expected_output = "tests/unit/fixtures/expected.out"

        with open(test_output, "w") as sys.stdout:
            catalog = discover()
            sync(fixtures.get_mock_config(), None, catalog)
            assert(filecmp.cmp(test_output, expected_output))
        os.remove(test_output)

def test_discover():
    catalog = discover()
    expected_catalog = {
        'streams':[
            {
                'stream':'logins',
                'tap_stream_id':'logins',
                'schema':{
                    'items':{
                    'type':'object',
                    'additionalProperties':False,
                    'properties':{
                        'id':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'timestamp':{
                            'type':[
                                'null',
                                'string'
                            ],
                            'format':'date-time'
                        },
                        'datacenter':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'source':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'descriptor':{
                            'type':[
                                'object'
                            ]
                        }
                    }
                    }
                },
                'metadata':{
                    'selected':True
                },
                'key_properties':[
                    
                ]
            },
            {
                'stream':'session_creations',
                'tap_stream_id':'session_creations',
                'schema':{
                    'items':{
                    'type':'object',
                    'additionalProperties':False,
                    'properties':{
                        'id':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'timestamp':{
                            'type':[
                                'null',
                                'string'
                            ],
                            'format':'date-time'
                        },
                        'datacenter':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'source':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'descriptor':{
                            'type':[
                                'object'
                            ]
                        }
                    }
                    }
                },
                'metadata':{
                    'selected':True
                },
                'key_properties':[
                    
                ]
            },
            {
                'stream':'session_terminations',
                'tap_stream_id':'session_terminations',
                'schema':{
                    'items':{
                    'type':'object',
                    'additionalProperties':False,
                    'properties':{
                        'id':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'timestamp':{
                            'type':[
                                'null',
                                'string'
                            ],
                            'format':'date-time'
                        },
                        'datacenter':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'source':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'descriptor':{
                            'type':[
                                'object'
                            ]
                        }
                    }
                    }
                },
                'metadata':{
                    'selected':True
                },
                'key_properties':[
                    
                ]
            },
            {
                'stream':'password_changes',
                'tap_stream_id':'password_changes',
                'schema':{
                    'items':{
                    'type':'object',
                    'additionalProperties':False,
                    'properties':{
                        'id':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'timestamp':{
                            'type':[
                                'null',
                                'string'
                            ],
                            'format':'date-time'
                        },
                        'datacenter':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'source':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'descriptor':{
                            'type':[
                                'object'
                            ]
                        }
                    }
                    }
                },
                'metadata':{
                    'selected':True
                },
                'key_properties':[
                    
                ]
            },
            {
                'stream':'password_resets',
                'tap_stream_id':'password_resets',
                'schema':{
                    'items':{
                    'type':'object',
                    'additionalProperties':False,
                    'properties':{
                        'id':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'timestamp':{
                            'type':[
                                'null',
                                'string'
                            ],
                            'format':'date-time'
                        },
                        'datacenter':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'source':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'descriptor':{
                            'type':[
                                'object'
                            ]
                        }
                    }
                    }
                },
                'metadata':{
                    'selected':True
                },
                'key_properties':[
                    
                ]
            },
            {
                'stream':'users',
                'tap_stream_id':'users',
                'schema':{
                    'items':{
                    'type':'object',
                    'additionalProperties':False,
                    'properties':{
                        'id':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'timestamp':{
                            'type':[
                                'null',
                                'string'
                            ],
                            'format':'date-time'
                        },
                        'datacenter':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'source':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'descriptor':{
                            'type':[
                                'object'
                            ]
                        }
                    }
                    }
                },
                'metadata':{
                    'selected':True
                },
                'key_properties':[
                    
                ]
            },
            {
                'stream':'brands',
                'tap_stream_id':'brands',
                'schema':{
                    'items':{
                    'type':'object',
                    'additionalProperties':False,
                    'properties':{
                        'id':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'timestamp':{
                            'type':[
                                'null',
                                'string'
                            ],
                            'format':'date-time'
                        },
                        'datacenter':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'source':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'descriptor':{
                            'type':[
                                'object'
                            ]
                        }
                    }
                    }
                },
                'metadata':{
                    'selected':True
                },
                'key_properties':[
                    
                ]
            },
            {
                'stream':'role_membership_change',
                'tap_stream_id':'role_membership_change',
                'schema':{
                    'items':{
                    'type':'object',
                    'additionalProperties':False,
                    'properties':{
                        'id':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'timestamp':{
                            'type':[
                                'null',
                                'string'
                            ],
                            'format':'date-time'
                        },
                        'datacenter':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'source':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'descriptor':{
                            'type':[
                                'object'
                            ]
                        }
                    }
                    }
                },
                'metadata':{
                    'selected':True
                },
                'key_properties':[
                    
                ]
            },
            {
                'stream':'role_permission_change',
                'tap_stream_id':'role_permission_change',
                'schema':{
                    'items':{
                    'type':'object',
                    'additionalProperties':False,
                    'properties':{
                        'id':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'timestamp':{
                            'type':[
                                'null',
                                'string'
                            ],
                            'format':'date-time'
                        },
                        'datacenter':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'source':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'descriptor':{
                            'type':[
                                'object'
                            ]
                        }
                    }
                    }
                },
                'metadata':{
                    'selected':True
                },
                'key_properties':[
                    
                ]
            },
            {
                'stream':'user_permission_change',
                'tap_stream_id':'user_permission_change',
                'schema':{
                    'items':{
                    'type':'object',
                    'additionalProperties':False,
                    'properties':{
                        'id':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'timestamp':{
                            'type':[
                                'null',
                                'string'
                            ],
                            'format':'date-time'
                        },
                        'datacenter':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'source':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'descriptor':{
                            'type':[
                                'object'
                            ]
                        }
                    }
                    }
                },
                'metadata':{
                    'selected':True
                },
                'key_properties':[
                    
                ]
            },
            {
                'stream':'contact_list',
                'tap_stream_id':'contact_list',
                'schema':{
                    'items':{
                    'type':'object',
                    'additionalProperties':False,
                    'properties':{
                        'id':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'timestamp':{
                            'type':[
                                'null',
                                'string'
                            ],
                            'format':'date-time'
                        },
                        'datacenter':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'source':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'descriptor':{
                            'type':[
                                'object'
                            ]
                        }
                    }
                    }
                },
                'metadata':{
                    'selected':True
                },
                'key_properties':[
                    
                ]
            },
            {
                'stream':'contact',
                'tap_stream_id':'contact',
                'schema':{
                    'items':{
                    'type':'object',
                    'additionalProperties':False,
                    'properties':{
                        'id':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'timestamp':{
                            'type':[
                                'null',
                                'string'
                            ],
                            'format':'date-time'
                        },
                        'datacenter':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'source':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'descriptor':{
                            'type':[
                                'object'
                            ]
                        }
                    }
                    }
                },
                'metadata':{
                    'selected':True
                },
                'key_properties':[
                    
                ]
            },
            {
                'stream':'directory',
                'tap_stream_id':'directory',
                'schema':{
                    'items':{
                    'type':'object',
                    'additionalProperties':False,
                    'properties':{
                        'id':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'timestamp':{
                            'type':[
                                'null',
                                'string'
                            ],
                            'format':'date-time'
                        },
                        'datacenter':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'source':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'descriptor':{
                            'type':[
                                'object'
                            ]
                        }
                    }
                    }
                },
                'metadata':{
                    'selected':True
                },
                'key_properties':[
                    
                ]
            },
            {
                'stream':'directory_setting',
                'tap_stream_id':'directory_setting',
                'schema':{
                    'items':{
                    'type':'object',
                    'additionalProperties':False,
                    'properties':{
                        'id':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'timestamp':{
                            'type':[
                                'null',
                                'string'
                            ],
                            'format':'date-time'
                        },
                        'datacenter':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'source':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'descriptor':{
                            'type':[
                                'object'
                            ]
                        }
                    }
                    }
                },
                'metadata':{
                    'selected':True
                },
                'key_properties':[
                    
                ]
            },
            {
                'stream':'dashboard_usage',
                'tap_stream_id':'dashboard_usage',
                'schema':{
                    'items':{
                    'type':'object',
                    'additionalProperties':False,
                    'properties':{
                        'id':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'timestamp':{
                            'type':[
                                'null',
                                'string'
                            ],
                            'format':'date-time'
                        },
                        'datacenter':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'source':{
                            'type':[
                                'null',
                                'string'
                            ]
                        },
                        'descriptor':{
                            'type':[
                                'object'
                            ]
                        }
                    }
                    }
                },
                'metadata':{
                    'selected':True
                },
                'key_properties':[
                    
                ]
            }
        ]
    }
    assert(catalog == expected_catalog)
