{{
  config(
    tags=['classification.c2_restricted']
  )
}}

with lead_snapshot as (

    select * from {{ ref('snapshot_sfdc_leads') }}

)

select 
    --ids
    id as sfdc_lead_id,
    {{ dbt_utils.surrogate_key(['id','dbt_valid_from','dbt_valid_to']) }} as history_primary_key,
    owner_id as lead_owner_id,
    created_by_id as lead_created_by_id,
    trac_rtc_account_c as sfdc_account_id,
    converted_contact_id,
    converted_date,
    'lead' as sfdc_record_type,

    --categorical and text attributes
    first_name,
    last_name,
    company as company_name,
    email,
    split_part(email, '@', 2) as email_domain,
    title as job_title,
    country as person_country,
    state as person_state,
    status as lead_status,
    booking_status_cp_c as booking_status,
    role_level_c as role_level,
    company_size_c as company_size,
    job_function_mkto_c as job_function,
    first_conversion_c as first_conversion,
    recent_conversion_c as recent_conversion,
    prospect_type_c as prospect_type,
    latest_source_c as latest_source,
    latest_source_drill_down_1_c as latest_source_drill_down_1,
    latest_source_drill_down_2_c as latest_source_drill_down_2,
    original_source_c as original_source,
    original_source_drill_down_1_c as original_source_drill_down_1,
    original_source_drill_down_2_c as original_source_drill_down_2,
    content_syndication_asset_download_c as content_syndication_asset_download,
   
    --outreach fields
    currently_active_sequence_outreach_c as currently_active_outreach_sequence,
    current_sequence_step_number_outreach_c as current_sequence_step,
    current_sequence_step_type_outreach_c as current_sequence_step_type,
    current_sequence_status_outreach_c as current_sequence_status,
    current_sequence_task_due_date_outreeac_c as current_sequence_task_due_date,
    finished_sequences_c as finished_sequences,
    number_of_active_tasks_outreach_c as number_of_active_tasks,
    number_of_active_sequences_outreach_c as number_of_active_sequences,

    mkto_71_lead_score_c as person_score,
    surge_score_c as mql_score,
    behavioral_score_c as behavioral_score,
    demographic_score_c as demographic_score,

    --quantities

    
    --boooleans
    has_opted_out_of_email,
  
    --dates and timestamps
    {{ load_timestamp('created_date', alias='created_at') }},
    {{ load_timestamp('last_modified_date', alias='last_modified_at') }},
    first_conversion_date_c as first_conversion_date,
    recent_conversion_date_c as recent_conversion_date,

    --other
    is_deleted,
    is_converted,
    dbt_valid_from as valid_from,
    dbt_valid_to as valid_to,
    dbt_valid_to is null as is_current_version,
    row_number() over(
      partition by id
      order by dbt_valid_from
    ) as version,

    case when
      row_number() over(
        partition by id,date_trunc('day',dbt_valid_from)
        order by dbt_valid_from desc
      ) = 1 then true else false end as is_last_snapshot_of_day,
    
    -- Additional fields for Looker View parity
    cfcr_status_reason_c,
    dscorgpkg_reports_to_c,
    lead_source_detail_c,
    mkto_si_urgency_value_c,
    dscorgpkg_ownership_c,
    master_record_id,
    mkto_71_original_source_type_c,
    referring_coach_referral_reason_c,
    trac_rtc_traction_complete_status_c,
    bdr_lead_owner_c,
    trac_rtc_date_of_last_completion_c,
    dscorgpkg_exclude_update_c,
    dscorgpkg_twitter_url_c,
    mkto_71_original_search_engine_c,
    current_sequence_owner_outreach_c,
    interest_c,
    postal_code,
    associated_e_value_prompter_c,
    cfcr_sql_date_c,
    city,
    email_bounced_date,
    data_quality_score_c,
    dscorgpkg_company_hq_address_c,
    dscorgpkg_job_function_c,
    dscorgpkg_management_level_c,
    mkto_71_original_search_phrase_c,
    mobile_phone,
    phone,
    do_not_route_c,
    dscorgpkg_fiscal_year_end_c,
    fcrm_fcr_post_assign_notification_pending_c,
    last_viewed_date,
    trac_rtc_d_b_match_grade_c,
    trac_rtc_sic_code_c,
    lead_source,
    mkto_71_inferred_postal_code_c,
    registration_status_c,
    type_c,
    dscorgpkg_fortune_rank_c,
    dscorgpkg_linked_in_url_c,
    notes_mkto_c,
    territory_c,
    dscorgpkg_do_3_yr_employees_growth_c,
    last_referenced_date,
    dscorgpkg_company_hq_country_full_name_c,
    fcrm_fcr_defer_assignment_c,
    owned_by_user_c,
    system_modstamp,
    trac_rtc_realtime_clean_processed_c,
    lead_rating_c,
    mkto_71_inferred_phone_area_code_c,
    last_activity_date,
    trac_rtc_re_run_realtime_clean_c,
    website,
    dscorgpkg_company_hq_postal_code_c,
    fcrm_fcr_created_by_lead_conversion_c,
    persons_evaluating_better_up_c,
    dscorgpkg_discover_org_last_update_c,
    is_mql_c,
    data_quality_description_c,
    fcrm_fcr_response_score_c,
    in_nurture_c,
    mkto_71_acquisition_program_id_c,
    prospecting_status_c,
    actively_being_sequenced_outreach_c,
    dscorgpkg_discover_org_id_c,
    dscorgpkg_do_3_yr_sales_growth_c,
    jigsaw,
    mkto_71_original_referrer_c,
    mkto_si_add_to_marketo_campaign_c,
    trac_rtc_ddc_company_id_c,
    cfcr_admin_score_increment_audit_c,
    is_lead_owner_ae_c,
    email_bounced_reason,
    fcrm_fcr_take_scoring_snapshot_c,
    nurture_exit_date_c,
    referring_coach_email_c,
    do_not_call,
    mkto_71_inferred_company_c,
    mkto_si_urgency_c,
    trac_rtc_contact_c,
    fcrm_fcr_admin_update_counter_c,
    mkto_si_priority_c,
    salutation,
    street,
    total_outreach_c,
    trac_rtc_traction_complete_domain_c,
    call_count_c,
    dscorgpkg_company_phone_c,
    linked_in_profile_c,
    marketing_opt_out_c,
    photo_url,
    cfcr_fccrm_threshold_c,
    owner_name_text_c,
    sdr_owner_lead_email_c,
    d_b_industry_c,
    mkto_71_original_source_info_c,
    is_coach_c,
    referring_coach_phone_number_c,
    trac_rtc_original_lead_data_c,
    dscorgpkg_company_hq_country_code_c,
    dscorgpkg_company_hq_state_c,
    dscorgpkg_external_discover_org_id_c,
    converted_account_id,
    d_b_last_update_c,
    uuid_ts,
    bdr_abm_outreach_c,
    cfcr_first_meeting_date_c,
    nurture_entry_date_c,
    outreach_pdf_name_c,
    is_unread_by_owner,
    mkto_71_inferred_metropolitan_area_c,
    name,
    trac_rtc_disable_complete_c,
    dscorgpkg_discover_org_technologies_c,
    referring_coach_full_name_c,
    suppression_c,
    dscorgpkg_itorg_chart_c,
    mkto_si_relative_score_value_c,
    outreach_id_c,
    target_account_c,
    trac_rtc_realtime_clean_company_match_c,
    d_b_email_c,
    outreach_event_name_c,
    outreach_status_c,
    outreach_url_c,
    mkto_71_inferred_state_region_c,
    promo_code_c,
    trac_rtc_sic_desc_c,
    fcrm_fcr_trigger_engagement_data_rebuild_c,
    lead_stage_c,
    mkto_si_view_in_marketo_c,
    no_longer_w_account_c,
    account_tier_c,
    calendly_created_c,
    check_in_status_c,
    dscorgpkg_discover_org_first_update_c,
    last_modified_by_id,
    mkto_si_last_interesting_moment_date_c,
    d_b_title_c,
    dscorgpkg_naics_codes_c,
    dscorgpkg_sic_codes_c,
    trac_rtc_traction_complete_status_text_c,
    development_areas_of_focus_c,
    rating,
    trac_rtc_realtime_clean_error_message_c,
    trac_rtc_realtime_clean_failed_c,
    dscorgpkg_it_employees_c,
    mkto_si_last_interesting_moment_source_c,
    received_at,
    dscorgpkg_discover_org_company_id_c,
    mkto_71_inferred_city_c,
    mkto_si_hide_date_c,
    mkto_si_last_interesting_moment_c,
    mkto_si_last_interesting_moment_type_c,
    middle_name,
    fcrm_fcr_status_last_set_c,
    outreached_approved_c,
    trac_rtc_traction_complete_lead_match_c,
    dscorgpkg_company_hq_city_c,
    fcrm_fcr_stage_age_c,
    jigsaw_contact_id,
    trac_rtc_d_b_match_confidence_c,
    higher_ed_four_year_institution_c,
    mkto_71_acquisition_date_c,
    mkto_si_relative_score_c,
    bizzabo_event_id_c,
    converted_opportunity_id,
    dscorgpkg_conflict_c,
    suffix,
    fcrm_fcr_name_created_date_c,
    dscorgpkg_discover_org_created_on_c,
    dscorgpkg_discover_org_full_country_name_c,
    email_count_c,
    referring_coach_relationship_to_prospect_c,
    trac_rtc_naics_code_c,
    description_mkto_c,
    integrate_source_id_c,
    trac_rtc_match_type_c,
    trac_rtc_naics_desc_c,
    trac_rtc_original_completion_date_c,
    dscorgpkg_deleted_from_discover_org_c,
    trac_rtc_realtime_clean_contact_match_c,
    employees_on_linked_in_outreach_c,
    fcrm_fcr_status_synced_from_response_c,
    industry,
    cfcr_response_c,
    dscorgpkg_company_hq_state_full_name_c,
    dscorgpkg_discover_org_state_full_name_c,
    is_ooto_c,
    last_engagement_date_c,
    outreach_webinar_name_c,
    cfcr_admin_score_increment_c,
    mkto_71_acquisition_program_c,
    mkto_si_last_interesting_moment_desc_c,
    account_type_c,
    dscorgpkg_department_c,
    dscorgpkg_it_budget_c,
    mkto_71_inferred_country_c,
    number_of_seats_requested_c,
    trac_rtc_global_ultimate_duns_number_c,
    hq_phone_c,
    number_of_employees,
    current_program_membership_c,
    dscorgpkg_email_invalid_c,
    sfdc_campaign_id_c,
    i_sell_oskey_id_c,
    d_b_function_c,
    recent_lead_activity_count_temp_c,
    double_opt_in_c,
    groove_last_touch_c,
    account_owner_region_c,
    utm_term_c,
    active_working_exit_date_c,
    third_party_lead_source_c,
    opt_in_c,
    better_up_last_touch_program_id_c,
    high_value_c,
    third_party_lead_owner_c,
    utm_source_c,
    better_up_last_touch_program_c,
    account_territory_c,
    da_scoop_composer_normalized_mobile_c,
    account_id_c,
    ga_cid_c,
    groove_last_touch_type_c,
    groove_last_flow_name_c,
    community_marketing_contact_c,
    double_opt_out_date_c,
    account_owner_c,
    bombora_avg_composite_score_c,
    bombora_topic_count_c,
    da_scoop_composer_normalized_phone_c,
    ga_id_c,
    groove_last_engagement_c,
    requested_demo_c,
    marketo_unique_id_c,
    utm_campaign_c,
    utm_content_c,
    groove_outbound_email_counter_c,
    opt_out_date_c,
    requested_demo_date_c,
    utm_medium_c,
    groove_last_flow_step_number_c,
    da_scoop_composer_groove_log_a_call_c,
    groove_last_flow_status_c,
    bombora_composite_score_sum_c,
    da_scoop_composer_groove_convert_c,
    is_converted_c,
    lead_interest_c,
    given_to_obview_c,
    groove_last_engagement_type_c,
    groove_engagement_score_c,
    auto_convert_c,
    groove_last_flow_step_type_c,
    groove_last_step_completed_c,
    owner_active_c,
    is_deal_registration_lead_c,
    better_up_opt_in_program_c,
    better_up_opt_in_program_id_c,
    opt_in_date_c,
    how_you_hope_to_work_with_bu_c,
    marketo_unique_code_c,
    break_out_session_c,
    double_opt_in_date_c,
    dozisf_zoom_info_company_id_c,
    dozisf_zoom_info_last_updated_c,
    dozisf_zoom_info_id_c,
    dozisf_zoom_info_first_updated_c,
    estimated_deal_size_c,
    partner_phone_c,
    business_unit_c,
    partner_email_c,
    partner_company_c,
    partner_name_c,
    survey_url_c,
    help_needed_from_bu_c,
    partner_type_c,
    average_client_company_size_c,
    how_did_you_hear_about_bu_c,
    currently_a_bu_coach_member_c,
    of_clients_c,
    pain_point_c,
    training_tactic_c,
    page_prior_to_demo_req_c,
    time_frame_c,
    da_scoop_composer_groove_notes_c,
    lt_utm_campaign_c,
    ft_utm_source_c,
    lt_utm_medium_c,
    ft_utm_medium_c,
    lt_utm_content_c,
    ft_utm_campaign_c,
    lt_utm_source_c,
    lt_referrer_c,
    ft_utm_term_c,
    ft_utm_content_c,
    lt_utm_term_c,
    lid_linked_in_company_id_c,
    d_b_phone_c,
    x6_sense_lead_account_6_qa_c,
    gclid_c,
    trac_rtc_traction_complete_custom_match_c,
    currency_iso_code,
    trac_rtc_time_delay_processed_c,
    mql_campaign_type_c,
    sdr_on_account_c,
    outreach_mql_c,
    mql_tier_c,
    outreach_demo_requested_c,
    ft_utm_camp_c,
    account_segment_c,
    abm_prospect_c

from lead_snapshot l
where coalesce(l.trac_rtc_account_c,'unknown') != '00150000025c8DOAAY' --this is a test account in salesforce
