with source as (

    select * from {{ source('salesforce', 'tasks') }}

),

renamed as (

    select
        id as task_id,
        call_disposition,
        data_quality_description_c,
        first_meeting_scheduled_c,
        last_modified_by_id,
        recurrence_end_date_only,
        recurrence_type,
        enablement_subject_c,
        owner_id,
        is_closed,
        pre_opportunity_sbs_involvement_c,
        priority,
        status,
        subject,
        type,
        what_count,
        what_id,
        recurrence_time_zone_sid_key,
        data_quality_score_c,
        driver_executor_attended_the_meeting_c,
        last_modified_date,
        who_count,
        created_date_c,
        evp_action_c,
        influencer_attended_the_meeting_c,
        is_recurrence,
        call_duration_in_seconds,
        decision_maker_attended_the_meeting_c,
        uuid_ts,
        call_object,
        enablement_task_sequence_c,
        is_reminder_set,
        recurrence_activity_id,
        task_subtype,
        enablement_link_c,
        first_meeting_rescheduled_c,
        in_person_meeting_c,
        overall_quality_score_c,
        recurrence_interval,
        recurrence_start_date_only,
        who_id,
        account_qbr_meeting_c,
        description,
        reminder_date_time,
        activity_date,
        call_type,
        created_by_id,
        first_meeting_c,
        received_at,
        system_modstamp,
        first_meeting_cancelled_c,
        who_will_be_evaluating_c,
        account_id,
        record_type_id,
        social_selling_generated_c,
        created_date,
        enablement_rationale_c,
        is_archived,
        is_deleted,
        phase_c,
        recurrence_day_of_month,
        is_high_priority,
        contact_or_lead_id_c,
        opp_amount_c,
        contact_id_18_digit_c,
        manager_c,
        groove_email_sent_at_c,
        da_scoop_composer_times_opened_c,
        da_scoop_composer_v_cal_iid_c,
        da_scoop_composer_times_clicked_c,
        global_account_manager_c,
        expected_revenue_c,
        documents_attached_to_opp_c,
        flow_name_c,
        groove_inbound_response_time_seconds_c,
        da_scoop_composer_last_opened_date_c,
        da_scoop_composer_v_cal_uid_c,
        assigned_to_region_c,
        da_scoop_composer_is_created_by_groove_c,
        da_scoop_composer_last_modified_date_c,
        groove_sent_from_flow_c,
        da_scoop_composer_mirror_in_owner_s_calendar_c,
        da_scoop_composer_replied_c,
        steer_co_del_c,
        template_name_c,
        opp_owner_region_c,
        opp_stage_c,
        qualified_by_c,
        opp_forecast_c,
        fm_opportunity_c,
        opp_type_c,
        notes_and_observations_c

    from source

)

select * from renamed
