with source as (

    select * from {{ source('salesforce', 'events') }}

),

renamed as (

    select
        id as events_id,
        how_well_was_prospect_aligned_on_meeting_c,
        recurrence_interval,
        recurrence_time_zone_sid_key,
        uuid_ts,
        what_count,
        social_selling_generated_c,
        additional_thoughts_c,
        first_meeting_rescheduled_c,
        last_modified_by_id,
        prospect_wants_to_accomplish_in_meeting_c,
        recurrence_start_date_time,
        influencer_attended_the_meeting_c,
        is_reminder_set,
        subject,
        activity_date_time,
        created_date_c,
        end_date_time,
        first_meeting_c,
        group_event_type,
        is_recurrence,
        overall_how_qualified_was_the_meeting_c,
        rate_your_satisfcation_of_meeting_setup_c,
        who_will_be_evaluating_c,
        who_count,
        duration_in_minutes,
        in_the_meeting_you_were_able_to_complete_c,
        invitee_uuid_c,
        record_type_id,
        recurrence_activity_id,
        pre_opportunity_sbs_involvement_c,
        recurrence_day_of_week_mask,
        account_id,
        account_qbr_meeting_c,
        additional_meeting_attendees_c,
        last_modified_date,
        meeting_outcomes_c,
        scheduled_by_c,
        what_is_your_best_guess_for_a_close_date_c,
        account_qbr_period_c,
        how_prospect_envisions_using_better_up_c,
        is_archived,
        number_of_people_being_coached_c,
        overall_quality_score_c,
        description,
        recurrence_instance,
        is_child,
        is_group_event,
        received_at,
        type,
        who_id,
        in_person_meeting_c,
        location,
        notes_and_observations_c,
        activity_date,
        did_prospect_agree_to_a_2_nd_meeting_c,
        driver_executor_attended_the_meeting_c,
        event_subtype,
        evp_action_c,
        owner_id,
        recurrence_type,
        created_date,
        first_meeting_cancelled_c,
        is_all_day_event,
        show_as,
        reminder_date_time,
        start_date_time,
        system_modstamp,
        data_quality_description_c,
        data_quality_score_c,
        decision_maker_attended_the_meeting_c,
        prospects_current_l_d_initiatives_c,
        recurrence_end_date_only,
        created_by_id,
        did_anyone_with_authority_attend_c,
        first_meeting_scheduled_c,
        is_deleted,
        meeting_objective_c,
        is_private,
        what_id,
        manager_c,
        contact_id_18_digit_c,
        contact_or_lead_id_c,
        opp_amount_c,
        campaign_tactic_c,
        fm_campaign_c,
        channel_c,
        super_channel_c,
        campaign_type_c,
        opp_stage_c,
        opp_type_c,
        fm_opportunity_c,
        opp_forecast_c,
        opp_owner_region_c,
        da_scoop_composer_is_created_by_groove_c,
        expected_revenue_c,
        account_qbr_status_c,
        marketing_program_c,
        publisher_c,
        da_scoop_composer_v_cal_uid_c,
        documents_attached_to_opp_c,
        steer_co_del_c,
        qbr_meeting_type_c,
        da_scoop_composer_last_modified_date_c,
        da_scoop_composer_mirror_in_owner_s_calendar_c,
        assigned_to_region_c,
        da_scoop_composer_replied_c,
        da_scoop_composer_times_opened_c,
        groove_sent_from_flow_c,
        region_c,
        da_scoop_composer_v_cal_iid_c,
        global_account_manager_c,
        account_qbr_c,
        qualified_by_c,
        use_case_c,
        coach_feedback_c

    from source

)

select * from renamed
