{{
  config(
    tags=['classification.c2_restricted']
  )
}}

select 

  id as sfdc_campaign_id,
  parent_id as parent_sfdc_campaign_id,
  publisher_c as publisher,
  name as campaign_name,
  channel_c as channel,
  super_channel_c as super_channel_raw,

  case
    when super_channel_c = 'BDR'
      then 'SDR'
    when super_channel_c in ('Referral','Alliances')
      then 'Referral/Alliances'
    else super_channel_c end as super_channel,
    
  marketing_program_c as marketing_program,
  fcrm_fcr_campaign_sourced_by_c as campaign_sourced_by,
  tactic_c as tactic,
  type as campaign_type,
  auidence_c as audience,
  content_title_c as content_title,
  budgeted_cost,
  currency_iso_code,
  is_deleted,

  -- Additional fields for Looker View Parity
  actual_cost,
  amount_all_opportunities,
  amount_won_opportunities,
  budget_category_c,
  campaign_briefing_c,
  campaign_plan_c,
  campaign_resources_c,
  cfcr_exclude_from_campaign_influence_c,
  cfcr_fccrm_campaign_threshold_c,
  content_desciption_c,
  count_c,
  created_by_id,
  current_fm_to_opportunity_conv_rate_c,
  current_prospect_to_fm_conversion_rate_c,
  current_win_rate_c,
  data_quality_description_c,
  data_quality_score_c,
  description,
  dscorgpkg_suppress_from_discover_org_c,
  end_date,
  expected_first_meetings_c,
  expected_new_bookings_c,
  expected_new_customers_c,
  expected_new_opportuntiies_c,
  expected_participants_c,
  expected_response,
  expected_revenue,
  fcrm_fcr_bypass_nurture_timeout_c,
  fcrm_fcr_campaign_precedence_c,
  fcrm_fcr_campaign_sourced_by_c,
  fcrm_fcr_cascade_parent_id_c,
  fcrm_fcr_cascade_parent_c,
  fcrm_fcr_closed_op_revenue_model_1_c,
  fcrm_fcr_closed_op_revenue_model_2_c,
  fcrm_fcr_closed_op_revenue_model_3_c,
  fcrm_fcr_cost_per_response_c,
  fcrm_fcr_cost_per_response_with_repeats_c,
  fcrm_fcr_lost_op_revenue_model_1_c,
  fcrm_fcr_lost_op_revenue_model_2_c,
  fcrm_fcr_lost_op_revenue_model_3_c,
  fcrm_fcr_net_new_names_c,
  fcrm_fcr_net_new_response_ratio_c,
  fcrm_fcr_open_op_revenue_model_1_c,
  fcrm_fcr_open_op_revenue_model_2_c,
  fcrm_fcr_open_op_revenue_model_3_c,
  fcrm_fcr_qr_s_c,
  fcrm_fcr_qr_to_opportunity_ratio_c,
  fcrm_fcr_qualified_responses_with_repeats_c,
  fcrm_fcr_repeat_campaign_number_c,
  fcrm_fcr_repeat_response_timeout_segments_c,
  fcrm_fcr_repeat_responses_allowed_c,
  fcrm_fcr_responses_to_won_c,
  fcrm_fcr_total_responses_with_repeats_c,
  fcrm_fcr_total_op_revenue_model_1_c,
  fcrm_fcr_total_op_revenue_model_2_c,
  fcrm_fcr_total_op_revenue_model_3_c,
  fcrm_me_exclude_from_reactivation_c,
  fcsc_fcdsc_capture_digital_touch_data_c,
  highspot_campaign_page_c,
  is_active,
  last_modified_by_id,
  number_of_contacts,
  number_of_converted_leads,
  number_of_leads,
  number_of_opportunities,
  number_of_responses,
  number_of_won_opportunities,
  number_sent,
  owner_id,
  region_c,
  registration_page_c,
  start_date,
  status,
  sub_region_c

from {{ source('salesforce', 'campaigns') }}
