WITH source AS (

    SELECT * FROM {{ source('app_eu', 'coach_profiles') }}

),

renamed AS (

    SELECT
        id,
        uuid,
        created_at,
        updated_at,
        bio,
        coach_style_words,
        endorsement,
        experience_highlight,
        fountain_applicant_id,
        greatest_accomplishment,
        industries,
        invoices_with_shortlist,
        languages,
        last_book_read,
        max_member_count,
        member_endings_training_assigned_at,
        member_levels,
        most_grateful_for,
        on_demand,
        outlook,
        pick_rate,
        primary,
        qa,
        risk_level,
        staffable_state,
        tier,
        videochat_storage_persistence_enabled,
        videochat_transcription_enabled,
        next_coach_nps_at,
        clinical_experience,
        lgbtq,
        management_work_years,
        experience_country,
        clinical_corporate_years,
        industry_work_experience,
        coaching_hours,
        industry_coaching_experience,
        accredited_coaching,
        clinical_years,
        armed_forces,
        race_ethnicity,
        clinical_hours,
        additional_certifications,
        gender,
        function_coaching_experience,
        vp_leadership_org_size,
        topic_experience,
        exec_experience_org_size,
        function_work_experience,
        vp_leadership_years,
        accountability_style,
        new_member,
        resistant_member,
        professional_work_years,
        short_engagement,
        coaching_style,
        coaching_cloud,
        engaged_member_count,
        current_volunteer_member_count,
        country_of_residence,
        segment_priority_level,
        appointment_buffer_enabled,
        hiring_tier,
        currency_code,
        care,
        organization_block_list,
        "{{ environment_reserved_word_column('group') }}",
        group_coaching_session_url,
        peer,
        docebo_user_id,
        coaching_varieties,
        consumer_priority_level,
        consumer,
        workshops_bio,
        debrief360,
        currency_code_backup,
        tier_backup,
        eea_eligible,
        external_shortlist_id,
        account_qualifications,
        postgrad_qualifications,
        additional_qualifications,
        group_coaching_qualifications,
        segment_qualifications,
        certification_qualifications,
        on_demand_qualifications,
        product_qualifications,
        focus_qualifications,
        professional_qualifications,
        cohort

    FROM source

)

SELECT * FROM renamed
