openapi: 3.0.1
info:
  title: Monte Carlo Data Monitors
  description: >
    Data quality monitoring powered by [Monte Carlo Data](getmontecarlo.com).
  x-cortex-git:
    github:
      repository: betterup/betterup-analytics
  x-cortex-tag: betterup-analytics-montecarlo
  x-cortex-type: service
  x-cortex-link:
  - name: Analytics Confluence
    type: documentation
    url: https://betterup.atlassian.net/wiki/spaces/AN/overview
  x-cortex-owners:
  - name: betterup/data-operations-squad
    type: GROUP
  - name: betterup/analytics
    type: GROUP
  - type: SLACK
    channel: squad-data-ops
  - type: SLACK
    channel: guild-data
  x-cortex-service-groups:
  - external-system
  - tier-2
  x-cortex-custom-metadata:
    codeowner-path: .github/CODEOWNERS
