-- Anonymizing names and passwords
CREATE ACCOUNT "BETTERUPFEDDEV"
    ADMIN_NAME='********',
    ADMIN_PASSWORD='********',
    EMAIL='********',
    EDITION=ENTERPRISE, REGION=AWS_US_EAST_1, REGION_GROUP=PUBLIC;

CREATE ACCOUNT "BETTERUPFEDSTAGING"
    ADMIN_NAME='********',
    ADMIN_PASSWORD='********',
    EMAIL='********',
    EDITION=BUSINESS_CRITICAL, REGION=AWS_US_GOV_EAST_1, REGION_GROUP=AWS_US_GOV_EAST_1;

CREATE ACCOUNT "BETTERUPFEDPROD"
    ADMIN_NAME='********',
    ADMIN_PASSWORD='********',
    EMAIL='********',
    EDITION=BUSINESS_CRITICAL, REGION=AWS_US_GOV_EAST_1, REGION_GROUP=AWS_US_GOV_EAST_1;