[tool.poetry]
name = "bu-tap-semaphore"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "bu_tap_semaphore"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"
arrow = "^1.2.3"
click = "^8.1.3"
pipelinewise-target-snowflake = "^2.2.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
mock = "^5.0.1"
pylint = "^2.15.10"
requests-mock = "^1.10.0"
pytest-mock = "^3.10.0"
pytest-cov = "^4.0.0"

[tool.poetry.scripts]
bu-tap-semaphore = "bu_tap_semaphore.tap:main"
create-semaphore-configs = "bu_tap_semaphore.configs:create_configs"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
