[tool.poetry]
name = "bu-tap-fountain"
version = "0.1.0"
description = ""
authors = ["Lisa Xie <rui.xie@betterup.co>"]
readme = "README.md"
packages = [{include = "bu_tap_fountain"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"
click = "^8.1.3"
pipelinewise-target-snowflake = "^2.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
mock = "^5.0.1"
pylint = "^2.15.10"
requests-mock = "^1.10.0"
pytest-mock = "^3.10.0"
pytest-cov = "^4.0.0"

[tool.poetry.scripts]
bu-tap-fountain = "bu_tap_fountain.tap:main"
create-configs = "bu_tap_fountain.configs:create_configs"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
