name: DBT Snapshot

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run on schedule at minute 15 past every 4th hour.
  schedule:
    - cron: "15 */4 * * *"

# Allow one concurrent deployment
concurrency:
  group: "dbt_snapshot"
  cancel-in-progress: true

env:
  SNOWFLAKE_USER: "DBT_GITHUB_CI_USER"
  SNOWFLAKE_PASSWORD: ${{ secrets.DBT_GITHUB_CI_USER_PASSWORD }}
  SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_TARGET_ACCOUNT }}
  SLACK_WEBHOOK_URL: ${{ secrets.DATA_SLACK_WEBHOOK_URL }}
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  GITHUB_ACTION_URL: "https://github.com/betterup/betterup-analytics/actions/workflows/dbt_snapshot.yml"
  DEPLOYMENT_ENVIRONMENT: ${{ secrets.BETTERUP_ENVIRONMENT }}

jobs:
  dbt_run:
    name: DBT Snapshot
    strategy:
      fail-fast: false
      matrix:
        environment: ['US Prod','EU Prod']

    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    defaults:
      run:
        working-directory: warehouse

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install python dependencies
        # Retry 3 times before the install actually fails 
        run: |
          (echo "===== Install Attempt: 1 =====" && make installdeps) || \
          (echo "===== Install Attempt: 2 =====" && make installdeps) || \
          (echo "===== Install Attempt: 3 =====" && make installdeps) || \
          (echo "===== Install python dependencies step failed =====" && exit 1)

      - name: Write DBT configs
        run: |
          make writedbtconfig

      - name: Install DBT dependencies
        run: |
          poetry run dbt deps --target prod

      - name: Run US dbt snapshot
        if: matrix.environment == 'US Prod'
        run: poetry run dbt snapshot --target prod

      - name: Run EU dbt snapshot
        if: matrix.environment == 'EU Prod'
        run: poetry run dbt snapshot --selector job__eu_snapshots --target prod


      - name: Archive target artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dbt-build-artifacts
          path: |
            warehouse/target

      - name: Send GitHub Action data to Slack workflow
        id: send-slack-notification
        uses: slackapi/slack-github-action@v1.23.0
        if: failure()
        with:
          # Slack API Reference: 
          # https://api.slack.com/messaging/composing
          # https://api.slack.com/reference/messaging/payload
          payload: |
            {
              "channel": "warroom-data",
              "icon_emoji": ":dbt-logo:",
              "text": "DBT Run Failure. <${{ env.GITHUB_ACTION_URL }}|View here.>"
            }
