name: Pipeline - looker-s3-sync

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "10 */6 * * *"

env:
  LOOKER_AWS_BUCKET: "bu-s3-looker-logs"
  LOOKERSDK_BASE_URL: "https://betterup.looker.com:19999"
  LOOKERSDK_API_VERSION: "3.1"
  LOOKERSDK_VERIFY_SSL: true
  LOOKERSDK_CLIENT_ID: ${{secrets.LOOKERSDK_CLIENT_ID}}
  LOOKERSDK_CLIENT_SECRET: ${{secrets.LOOKERSDK_CLIENT_SECRET}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

  BU_SLACK_BOT_TOKEN: ${{ secrets.BU_SLACK_BOT_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.DATA_SLACK_WEBHOOK_URL }}
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  GITHUB_ACTION_URL: "https://github.com/betterup/betterup-analytics/actions/workflows/looker_s3_sync.yml"

jobs:
  looker-s3-sync:
    name: looker-s3-sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Setup poetry
        uses: snok/install-poetry@v1

      - name: Run looker-s3-sync job
        run: sudo chmod +x bin/looker-s3-sync && bin/looker-s3-sync

      - name: Send GitHub Action data to Slack workflow
        id: send-slack-notification
        uses: slackapi/slack-github-action@v1.23.0
        if: failure()
        with:
          payload: |
            {
              "channel": "warroom-data",
              "icon_emoji": ":github:",
              "text": "Pipeline Failure: ${{ github.workflow }} <${{ env.GITHUB_ACTION_URL }}|View here.>"
            }
